from datetime import date
from club import Club
from persona import Persona
from cuota import Cuota
from socio import Socio

fecha_antigua = date(2023, 5, 15)
socio1 = Socio(fecha_antigua, "Activo", "tio charly", "clave123", "Carlos Rodríguez", 30, "DNI", "30111222", "Argentina")
socio1.asociar_club("Malaga")
socio1.asociar_club("Madrid")
socio1.mostrar_clubes()
socio1.eliminar_club("Madrid")
socio1.mostrar_clubes()
socio1.generar_cuota(67, "Agosto", date(2026, 8, 10))
socio1.generar_cuota(76, "Septiembre", date(2026, 9, 10))
socio1.pagar_cuota(67)
socio1.tiene_deudas()
socio1.evaluar_suspension()
socio1.mostrar_cuotas_pendientes()
socio1.verificar_vencimiento_cuotas()
socio1.verificar_acceso("tio charly", "clave123")
socio1.reactivar_socio()
print("-----------------------------------------------------------------------------------------------")
persona1 = Persona("Juancito", 25, "DNI", "12345678", "Argentina")
persona1.mostrar_anio_donde_legalizo()
persona1.verificar_identificacion()
print("-----------------------------------------------------------------------------------------------")
cuota1 = Cuota("Pendiente", date(2026, 8, 10), "agosto")
cuota1.registrar_cuota_pagada()
cuota1.verificar_vencimiento()
cuota1.dias_para_vencimiento()
cuota1.renovar_cuota("septiembre", date(2026, 9, 10))
cuota1.actualizar_estado()
print("-----------------------------------------------------------------------------------------------")
club1 = Club("Madrid","chico, de 50 personas max","Malaga, España", "Ronaldo", 1998 )
club1.mostrar_info()
print("¿Es histórico?:", club1.es_historico())
club1.mostrar_antiguedad()
club2 = Club("Malaga","grande, de 250 personas max","Madrid, España", "Messi", 1894 )
club2.mostrar_info()
club2.mostrar_antiguedad()
print("¿Es histórico?:", club2.es_historico())